#!/bin/bash
# doit do naf2timelinejson-stuff
# 20150218 Paul Huygen
ROOT=$(cd `dirname "${BASH_SOURCE[0]}"` && pwd) &>/dev/null
PACKROOT=$ROOT/vua-naf2jsontimeline_2015
LIBDIR=$PACKROOT/lib
RESOURCESDIR=$PACKROOT/resources
DATASOURCEDIR=$PACKROOT/test/corpus_airbus
#WORKDIR=$ROOT/work
#WORKDIR=`mktemp -d -t time2json.XXXXXX`
WORKDIR=$1
EVENTSDIR=$WORKDIR/events
PRODUCT=$EVENTSDIR/contextual.timeline.json
#
# Java environment
#
JAVANS=eu.newsreader.eventcoreference
JAR=$LIBDIR/EventCoreference-1.0-SNAPSHOT-jar-with-dependencies.jar
CLUSTERMODULE=$JAVANS.naf.ClusterEventObjects
MATCHMODULE=$JAVANS.naf.MatchEventObjects
COREFMODULE=$JAVANS.input.TrigToJsonTimeLineClimax
#
# Get input NAF's
#
mkdir -p $WORKDIR
cd $WORKDIR
#cat | gawk -f $ROOT/splitnafs.awk 
#cp $DATASOURCEDIR/*.naf $WORKDIR

#
# Process
#
java -Xmx2000m -cp $JAR $CLUSTERMODULE --naf-folder $WORKDIR --event-folder "$WORKDIR" --extension ".naf" --project timeline --communication-frames "$RESOURCESDIR/communication.txt" --grammatical-frames "$RESOURCESDIR/grammatical.txt" --contextual-frames "$RESOURCESDIR/contextual.txt" --non-entities &>/dev/null

java -Xmx2000m -cp $JAR $MATCHMODULE $MATCHMODULE --match-type ililemma --ili-uri --event-folder "$WORKDIR/events/contextualEvent" --verbose --roles "a1" --concept-match 50 --phrase-match 50  --ili "$RESOURCESDIR/ili.ttl" &>/dev/null

java -Xmx2000m -cp $JAR $COREFMODULE --trig-folder "$WORKDIR/events/contextualEvent" --ili "$RESOURCESDIR/wn3-ili-synonyms.txt" --frame-relations "$RESOURCESDIR/frRelation.xml" --frame-level 3 &>/dev/null

#java -Xmx2000m -cp $JAR $COREFMODULE --trig-folder "$WORKDIR/events/contextual" --ili "$RESOURCESDIR/wn3-ili-synonyms.txt" --eso-relations "$RESOURCESDIR/ESO_version_0.6.owl" --eso-level 2 &>/dev/null

cat $PRODUCT
# rm -rf $WORKDIR
#java -Xmx2000m -cp ../lib/EventCoreference/target/EventCoreference-1.0-SNAPSHOT-jar-with-dependencies.jar eu.newsreader.eventcoreference.naf.ClusterEventObjects --microstories 4 --naf-folder "../tmp" --event-folder "../tmp" --extension ".naf" --project timeline --communication-frames "../resources/communication.txt" --grammatical-frames "../resources/grammatical.txt" --contextual-frames "../resources/contextual.txt" 
#
#java -Xmx2000m -cp ../lib/EventCoreference/target/EventCoreference-1.0-SNAPSHOT-jar-with-dependencies.jar eu.newsreader.eventcoreference.naf.MatchEventObjects --match-type ILILEMMA --ili-uri --event-folder "../tmp/events/contextual" --single-output --event-type "contextual"
#
#java -Xmx2000m -cp ../lib/EventCoreference/target/EventCoreference-1.0-SNAPSHOT-jar-with-dependencies.jar eu.newsreader.eventcoreference.input.TrigToJsonTimeLine --trig-folder "../tmp/events/contextual" --ili "../resources/wn3-ili-synonyms.txt" --actors fn
